import { NextResponse } from "next/server";

// GET - Listar ícones disponíveis
export async function GET() {
  try {
    // Lista de ícones populares do Lucide React organizados por categoria
    const icons = {
      food: [
        "Utensils",
        "Coffee",
        "Pizza",
        "Hamburger",
        "Cake",
        "IceCream",
        "Apple",
        "Carrot",
        "Fish",
        "Drumstick",
        "Wine",
        "Beer",
        "Milk",
        "Egg",
        "Bread",
        "Cheese",
        "Salad",
        "Soup",
        "Rice",
        "Noodles",
      ],
      general: [
        "Heart",
        "Star",
        "Fire",
        "Zap",
        "Sun",
        "Moon",
        "Cloud",
        "Rain",
        "Snow",
        "Wind",
        "Leaf",
        "Tree",
        "Flower",
        "Seedling",
        "Sprout",
        "Crown",
        "Gem",
        "Diamond",
        "Gift",
        "Party",
      ],
      objects: [
        "Home",
        "Building",
        "Store",
        "Shop",
        "Bag",
        "Package",
        "Box",
        "Container",
        "Bottle",
        "Glass",
        "Beaker",
        "Mug",
        "Plate",
        "Bowl",
        "Fork",
        "Knife",
        "Spoon",
        "Chopsticks",
        "Tray",
        "Dish",
      ],
      symbols: [
        "Plus",
        "Minus",
        "X",
        "Check",
        "Circle",
        "Square",
        "Triangle",
        "Diamond",
        "Hexagon",
        "Octagon",
        "Star",
        "Heart",
        "Infinity",
        "Target",
        "Cross",
        "Arrow",
        "ArrowUp",
        "ArrowDown",
        "ArrowLeft",
        "ArrowRight",
      ],
      nature: [
        "Mountain",
        "Tree",
        "Leaf",
        "Flower",
        "Rose",
        "Tulip",
        "Sunflower",
        "Cactus",
        "Palm",
        "Bamboo",
        "Grass",
        "Mushroom",
        "Seed",
        "Sprout",
        "Plant",
        "Garden",
        "Forest",
        "Park",
        "Beach",
        "Ocean",
      ],
      animals: [
        "Cat",
        "Dog",
        "Bird",
        "Fish",
        "Rabbit",
        "Horse",
        "Cow",
        "Pig",
        "Sheep",
        "Goat",
        "Chicken",
        "Duck",
        "Turkey",
        "Eagle",
        "Owl",
        "Penguin",
        "Dolphin",
        "Whale",
        "Shark",
        "Lion",
      ],
    };

    return NextResponse.json({
      success: true,
      icons,
      total: Object.values(icons).flat().length,
    });
  } catch (error) {
    console.error("Erro ao buscar ícones:", error);
    return NextResponse.json(
      { error: "Erro interno do servidor" },
      { status: 500 }
    );
  }
}
